CREATE TABLE IF NOT EXISTS application
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id   UUID        NOT NULL UNIQUE,
    created_at    TIMESTAMPTZ NOT NULL,
    status        VARCHAR(255),
    error_message TEXT
);

CREATE TABLE IF NOT EXISTS hash
(
    application_id BIGINT PRIMARY KEY,
    digest         TEXT         NOT NULL,
    algorithm      VARCHAR(255) NOT NULL,
    plaintext      TEXT,
    CONSTRAINT hash_application_id_fkey FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE
);